@{
  # Compatibility ruleset for the second pass in Tools/lint.ps1. General style rules run in
  # the first pass there; this file only checks cross-version / cross-platform use.
  #
  # Generated by Tools/prepare.ps1 from the '{{PlatformName}}' platform preset:
  # {{PlatformDescription}}
  # Edit freely - nothing regenerates it. Keep it in sync with the ci.yml matrix and
  # CompatiblePSEditions in the module manifest.
  IncludeRules = @(
    'PSUseCompatibleSyntax'
    'PSUseCompatibleCommands'
  )
  Rules = @{
      PSUseCompatibleSyntax = @{
          Enable         = $true
          TargetVersions = @({{TargetVersions}})
      }
      PSUseCompatibleCommands = @{
          Enable         = $true
          TargetProfiles = @(
{{TargetProfiles}}
          )
      }
  }
}
