@{
  # Compatibility ruleset for the second pass in Tools/lint.ps1. General style rules run in
  # the first pass there; this file only checks cross-version / cross-platform use.
  #
  # Generated by Tools/prepare.ps1 from the 'PowerShell5.1And7' platform preset:
  # Windows PowerShell 5.1 and PowerShell 7+ (Desktop and Core, Windows/Linux/macOS)
  # Edit freely - nothing regenerates it. Keep it in sync with the ci.yml matrix and
  # CompatiblePSEditions in the module manifest.
  IncludeRules = @(
    'PSUseCompatibleSyntax'
    'PSUseCompatibleCommands'
  )
  Rules = @{
      PSUseCompatibleSyntax = @{
          Enable         = $true
          TargetVersions = @('5.1', '7.0')
      }
      PSUseCompatibleCommands = @{
          Enable         = $true
          TargetProfiles = @(
              'win-8_x64_10.0.17763.0_5.1.17763.316_x64_4.0.30319.42000_framework'
              'win-8_x64_10.0.17763.0_7.0.0_x64_3.1.2_core'
              'ubuntu_x64_18.04_7.0.0_x64_3.1.2_core'
          )
      }
  }
}
